apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: gcr.io/class-mino-01/petclinic:5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests: ## 오토파일럿 모드에서 없으면 에러 발생 
            memory: "100Mi"
            cpu: "250m"
          limits: ## limit이 없으면 오토스케일링 문제 발생  
            cpu: "500m"
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
